### ISSUE TITLE
$\operatorname{-prod}\omega$ throws

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#383]
When activating the a11y extensions on mathjax.org, $\operatorname{-prod}\omega$ renders as "a is undefined". 

The MathML generated by MathJax passed to SRE 3.0.1 manually gives me

``` 
    `TypeError` was thrown:
        TypeError: Cannot read property 'dataset' of undefined
            at Object.sre.DomUtil.getDataAttribute (/node_modules/speech-rule-engine/lib/sre.js:134:53)
            at Object.sre.WalkerUtil.getAttribute (/node_modules/speech-rule-engine/lib/sre.js:573:476)
            at sre.RebuildStree.makeNode (/node_modules/speech-rule-engine/lib/sre.js:577:70)
            at sre.RebuildStree.assembleTree (/node_modules/speech-rule-engine/lib/sre.js:575:64)
            at sre.RebuildStree.e (/node_modules/speech-rule-engine/lib/sre.js:576:94)
            at Array.map (<anonymous>)
            at sre.RebuildStree.assembleTree (/node_modules/speech-rule-engine/lib/sre.js:576:148)
            at sre.RebuildStree.e (/node_modules/speech-rule-engine/lib/sre.js:576:94)
            at Array.map (<anonymous>)
            at sre.RebuildStree.assembleTree (/node_modules/speech-rule-engine/lib/sre.js:576:186)
```

**Comment by pkra** [comment]
This was fixed v3.1.
