### ISSUE TITLE
xml-dom-sre: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#487]
The innocuous looking expression `\theta |_{S(F)_r}` gives me a 

```
node_modules/xmldom-sre/dom.js:1283
                                return buf.join('');
                                           ^

RangeError: Maximum call stack size exceeded
    at Array.join (<anonymous>)
    at getTextContent (node_modules/xmldom-sre/dom.js:1283:16)
    at getTextContent (node_modules/xmldom-sre/dom.js:1279:16)
    at getTextContent (node_modules/xmldom-sre/dom.js:1279:16)
    at getTextContent (node_modules/xmldom-sre/dom.js:1279:16)
    at getTextContent (node_modules/xmldom-sre/dom.js:1279:16)
    at getTextContent (node_modules/xmldom-sre/dom.js:1279:16)
    at getTextContent (node_modules/xmldom-sre/dom.js:1279:16)
    at getTextContent (node_modules/xmldom-sre/dom.js:1279:16)
    at getTextContent (node_modules/xmldom-sre/dom.js:1279:16)
```

SRE config:

```
 sre.setupEngine({
    domain: 'mathspeak',
    style: 'default',
    locale: 'en',
    speech: 'deep',
    structure: true,
    mode: 'sync',
  });
```

## More examples

`{\operatorname {Cht}_{ I,W}^{(I)}} \big |_{(X\smallsetminus N)^{I}}`

`\chi |_{(\mathbb{Z}/p\mathbb{Z})^\times }=1`

`K= ||f||_{L^{\infty }(\Omega )}`

`\begin{equation*} B_*^{\xi }(\mathbb{D}^*)=\{\varphi \in B(\mathbb{D}^{*})\mid \forall \; \varepsilon \gt  0, \exists \; t \gt  0\quad \text{ such that}\; \Vert \varphi |_{\mathbb{D}^* \setminus (D_{t}^{\xi })^*} \Vert _B \lt  \varepsilon \}. \end{equation*} `

` \begin{equation*} \int _{\mathbb{G}}\frac{|f(x)|^{p}}{|x|^{Q}}dx\leq p\left(\int _{\mathbb{G}}\frac{|\mathbb{E}f(x)|^{p}|\log |x||^{p}}{|x|^{Q}}dx\right) ^{\frac{1}{p}}\left(\int _{\mathbb{G}}\frac{|f(x)|^{p}}{|x|^{Q}}dx\right)^{\frac{p-1}{p}}, \end{equation*} `

` \begin{equation*} ||f||^{2}_{L^2(X)}=\left(\sum _{j=0}^{\infty }\sum _{k=1}^{d_j}|\widehat{f}(j,k)|^{2}\right)^{1/2}=||\widehat{f}||^{2}_{l^{2}(\mathbb{N}_{0},\Sigma )}=:\sum _{j=0}^{\infty }||\widehat{f}(j)||^{2}_{\mathtt{HS}}, \end{equation*} `

**Comment by pkra** [comment]
This is with both 3.2.0-beta2 and beta 3.

**Comment by pkra** [comment]
Here's another one: `{\operatorname {Cht}_{ I,W}^{(I)}} \big |_{(X\smallsetminus N)^{I}}`

**Comment by pkra** [comment]
And another: `\chi |_{(\mathbb{Z}/p\mathbb{Z})^\times }=1`

**Comment by pkra** [comment]
These seem to be bugs dating back to 3.1.

**Comment by pkra** [comment]
I've updated the top card with all examples I've found so far.

**Comment by pkra** [comment]
On a related note, there's now an actively maintained fork of xmldom, https://github.com/xmldom/xmldom. Maybe worth a look.
