### ISSUE TITLE
sre.RebuildStree.assembleTree:  RangeError: Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by pkra** [zorkow/speech-rule-engine#489]
Possibly related to #487. In 3.2.0-beta2 the expression` \begin{equation*} \overset{s}{\underset{i=r}{\mathop {⨅}}} a_i=a_ra_{r-1}\cdots a_s. \end{equation*} ` gives me the following error:

```

node_modules/speech-rule-engine/lib/sre.js:624
sre.RebuildStree.prototype.assembleTree=function(a){var b=this.makeNode(a),c=sre.WalkerUtil.splitAttribute(sre.WalkerUtil.getAttribute(a,sre.EnrichMathml.Attribute.CHILDREN)),d=sre.WalkerUtil.splitAttribute(sre.WalkerUtil.getAttribute(a,sre.EnrichMathml.Attribute.CONTENT));sre.RebuildStree.addAttributes(b,a,!(c.length||d.length));if(0===d.length&&0===c.length)return b.textContent=a.textContent,b;if(0<d.length){var e=sre.WalkerUtil.getBySemanticId(a,d[0]);e&&(e=sre.WalkerUtil.splitAttribute(sre.WalkerUtil.getAttribute(e,
                                                ^

RangeError: Maximum call stack size exceeded
    at sre.RebuildStree.assembleTree (node_modules/speech-rule-engine/lib/sre.js:624:49)
    at sre.RebuildStree.e (node_modules/speech-rule-engine/lib/sre.js:625:132)
    at Array.map (<anonymous>)
    at sre.RebuildStree.assembleTree (node_modules/speech-rule-engine/lib/sre.js:625:224)
    at sre.RebuildStree.e (node_modules/speech-rule-engine/lib/sre.js:625:132)
    at Array.map (<anonymous>)
    at sre.RebuildStree.assembleTree (node_modules/speech-rule-engine/lib/sre.js:625:224)
    at sre.RebuildStree.e (node_modules/speech-rule-engine/lib/sre.js:625:132)
    at Array.map (<anonymous>)
    at sre.RebuildStree.assembleTree (node_modules/speech-rule-engine/lib/sre.js:625:224
```

This expression seems ok in 3.1 so this looks like a regression in 3.2.0-beta.

**Comment by zorkow** [comment]
Corner case of the new limit heuristic. Minimal example:
```
\overset{s}{\underset{i}{\mathop {⨅} a
```
